version: "3.3"
services: 
    postgresdb:
        image: postgres:latest
        env_file: 
            - .env
        ports: 
            - '5432:5432'
        volumes: 
            - data:/var/lib/postgres
        networks: 
            - mynetwork
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 30s
            timeout: 30s
            retries: 3

    redisdb:
        image: redis:latest
        ports: 
            - '6379:6379'
        env_file: 
            - .env
        volumes: 
            - data:/var/lib/redis
        networks: 
            - mynetwork
        command: redis-server --requirepass ${REDIS_PASSWORD}

    server:
        build: 
            context: .
            dockerfile: Dockerfile
        env_file: .env
        depends_on:
            - postgresdb
            - redisdb
        networks: 
            - mynetwork
        ports: 
            - '8080:8080'
        restart: on-failure
        links: 
            - postgresdb

networks: 
    mynetwork:
        driver: bridge

volumes: 
    data: